"""Generate MECHANISMS.md from the registry: every mechanism, its status,
version, parameters and assumptions. python -m learner.describe > MECHANISMS.md"""
from . import core  # noqa: F401  (registers everything)
from .config import VARIANTS
from .registry import REGISTRY


def main():
    used = {}
    for v, cfg in VARIANTS.items():
        for slot, spec in cfg.items():
            for s in (spec if isinstance(spec, list) else [spec]):
                used.setdefault((slot if slot != "evidence" else "evidence", s["name"]), []).append(v)
    print("# Registered mechanisms\n")
    print("Generated by `python -m learner.describe`. Every mechanism below is replaceable through "
          "`learner/config.py`; its tag (slot:name@version#params_hash) is written into every inference it produces.\n")
    for slot in sorted(REGISTRY):
        print(f"## Slot `{slot}`\n")
        for name, cls in REGISTRY[slot].items():
            m = cls()
            print(f"### `{name}` — {cls.STATUS}, v{cls.VERSION}\n")
            print(f"Used by variants: {', '.join(used.get((slot, name), [])) or 'none'}\n")
            print(f"Parameters: `{m.p}`\n" if m.p else "Parameters: none\n")
            for a in cls.ASSUMPTIONS:
                print(f"- {a}")
            print()


if __name__ == "__main__":
    main()
